config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'products#index'
  resources :products
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :title, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :title, presence: true
  validates_numericality_of :price, geater_than: 0
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.slim
= form_with(model: category, local: true) do |form|
  - if category.errors.any?
    #error_explanation
      h2
        = pluralize(category.errors.count, "error")
        |  prohibited this category from being saved:
      ul
        - category.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title, id: :category_title
  .field
    = form.label :description
    = form.text_area :description, id: :category_description
  .actions
    = form.submit

app/views/categories/edit.html.slim
h1
  | Editing Category
= render 'form', category: @category
= link_to 'Show', @category
|  | 
= link_to 'Back', categories_path

app/views/categories/index.html.slim
p#notice
  = notice
h1
  | Categories
table
  thead
    tr
      th
        | Title
      th
        | Description
      th[colspan="3"]
  tbody
    - @categories.each do |category|
      tr
        td
          = category.title
        td
          = category.description
        td
          = link_to 'Show', category
        td
          = link_to 'Edit', edit_category_path(category)
        td
          = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1
  | New Category
= render 'form', category: @category
= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @category.title
p
  strong
    | Description:
  = @category.description
= link_to 'Edit', edit_category_path(@category)
|  | 
= link_to 'Back', categories_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Testgem
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag Ckeditor.cdn_url
  body
    = yield

app/views/products/_form.html.slim
= semantic_form_for @product do |f|
  .field
    = f.label :title
    = f.input :title
  .field
    = f.label :description
    = f.cktext_area :description
  .field
    = f.label :price
    = f.input :price
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :category_id
    = f.input :category
  .actions
    = f.submit

app/views/products/edit.html.slim
h1
  | Editing Product
= render 'form', product: @product
= link_to 'Show', @product
|  | 
= link_to 'Back', products_path

app/views/products/index.html.slim
p#notice
  = notice
h1
  | Products
table.table.table-hover
  thead
    tr
      th
        | Title
      th
        | Description
      th
        | Price
      th
        | Category
      th[colspan="3"]
  tbody
    - @products.each do |product|
      tr
        td
          = product.title
        td
          = product.description
        td
          = product.price
        td
          = product.category.title
        td
          = link_to 'Show', product
        td
          = link_to 'Edit', edit_product_path(product)
        td
          = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1
  | New Product
= render 'form', product: @product
= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @product.title
p
  strong
    | Description:
  = @product.description.html_safe
p
  strong
    | Price:
  = @product.price
  strong
    |Image
  img src = @product.image(:medium)
p
  strong
    | Category:
  = @product.category.title
= link_to 'Edit', edit_product_path(@product)
|  |
= link_to 'Back', products_path